[package]
name = "fns"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.2.0"
thiserror = "1"

[dependencies.chumsky]
git = "https://github.com/zesterer/chumsky"
rev = "42d5af5a5710f6d60beedcde1904155e96451568"
