[package]
name = "fns"
version = "0.1.0"
edition = "2021"

[dependencies]
lasso = "0.7.0"
ariadne = "0.2.0"
thiserror = "1"

[dependencies.chumsky]
git = "https://github.com/zesterer/chumsky"
rev = "f664d7d7f36205bca58842233431927c14be69c0"
